on: [push]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Virus
        run: |
          wget https://secure.eicar.org/eicar.com
          wget https://secure.eicar.org/eicar.com.txt
          wget https://secure.eicar.org/eicar_com.zip
          wget https://secure.eicar.org/eicarcom2.zip
          tar -cvf eicar.com.tar eicar.com

      - name: History AV Scan
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Git AV Scan
        uses: djdefi/gitavscan@master
        with:
          full: '--full'
    
