on: [push]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    steps:
      - name: History checkout
        uses: actions/checkout@v2
        with:
          # Non-shallow
          fetch-depth: '0'
           
      - name: Download Test Virus
        run: |
          wget https://secure.eicar.org/eicar.com
          wget https://secure.eicar.org/eicar.com.txt
          wget https://secure.eicar.org/eicar_com.zip
          wget https://secure.eicar.org/eicarcom2.zip
          tar -cvf eicar.com.tar eicar.com
      
      - name: Git AV Scan (latest commit + working directory)
        uses: djdefi/gitavscan@master
      - name: Git AV Scan (full history)
        uses: djdefi/gitavscan@master
        with:
          full: '--full'
    
